# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import tree_pb2 as tree__pb2


class TreeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add_note_root = channel.unary_unary(
                '/rpc_package.TreeService/add_note_root',
                request_serializer=tree__pb2.rootAddRequest.SerializeToString,
                response_deserializer=tree__pb2.rootAddReply.FromString,
                )
        self.Stream = channel.unary_stream(
                '/rpc_package.TreeService/Stream',
                request_serializer=tree__pb2.Empty.SerializeToString,
                response_deserializer=tree__pb2.streamRequest.FromString,
                )


class TreeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add_note_root(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stream(self, request, context):
        """streaming functions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TreeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add_note_root': grpc.unary_unary_rpc_method_handler(
                    servicer.add_note_root,
                    request_deserializer=tree__pb2.rootAddRequest.FromString,
                    response_serializer=tree__pb2.rootAddReply.SerializeToString,
            ),
            'Stream': grpc.unary_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=tree__pb2.Empty.FromString,
                    response_serializer=tree__pb2.streamRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc_package.TreeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TreeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add_note_root(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpc_package.TreeService/add_note_root',
            tree__pb2.rootAddRequest.SerializeToString,
            tree__pb2.rootAddReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/rpc_package.TreeService/Stream',
            tree__pb2.Empty.SerializeToString,
            tree__pb2.streamRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
