# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tree.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tree.proto',
  package='rpc_package',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntree.proto\x12\x0brpc_package\"\x07\n\x05\x45mpty\"\x1f\n\rinsertRequest\x12\x0e\n\x06\x63lient\x18\x01 \x01(\t\">\n\x0binsertReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0e\n\x06minsup\x18\x02 \x01(\x02\x12\x0f\n\x07message\x18\x03 \x01(\t\">\n\x0erootAddRequest\x12\x0e\n\x06\x63lient\x18\x01 \x01(\t\x12\x0b\n\x03trx\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\xa4\x01\n\x0crootAddReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0e\n\x06\x63lient\x18\x02 \x01(\t\x12\x37\n\x07message\x18\x03 \x03(\x0b\x32&.rpc_package.rootAddReply.MessageEntry\x12\x0b\n\x03trx\x18\x04 \x01(\t\x1a.\n\x0cMessageEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"Q\n\rstreamRequest\x12\x0e\n\x06\x63lient\x18\x01 \x01(\t\x12\x0b\n\x03trx\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x12\n\naddNewItem\x18\x04 \x01(\x08\x32\x96\x01\n\x0bTreeService\x12I\n\radd_note_root\x12\x1b.rpc_package.rootAddRequest\x1a\x19.rpc_package.rootAddReply\"\x00\x12<\n\x06Stream\x12\x12.rpc_package.Empty\x1a\x1a.rpc_package.streamRequest\"\x00\x30\x01\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='rpc_package.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=34,
)


_INSERTREQUEST = _descriptor.Descriptor(
  name='insertRequest',
  full_name='rpc_package.insertRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client', full_name='rpc_package.insertRequest.client', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=67,
)


_INSERTREPLY = _descriptor.Descriptor(
  name='insertReply',
  full_name='rpc_package.insertReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='rpc_package.insertReply.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='minsup', full_name='rpc_package.insertReply.minsup', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='rpc_package.insertReply.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=131,
)


_ROOTADDREQUEST = _descriptor.Descriptor(
  name='rootAddRequest',
  full_name='rpc_package.rootAddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client', full_name='rpc_package.rootAddRequest.client', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trx', full_name='rpc_package.rootAddRequest.trx', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='rpc_package.rootAddRequest.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=195,
)


_ROOTADDREPLY_MESSAGEENTRY = _descriptor.Descriptor(
  name='MessageEntry',
  full_name='rpc_package.rootAddReply.MessageEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='rpc_package.rootAddReply.MessageEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='rpc_package.rootAddReply.MessageEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=362,
)

_ROOTADDREPLY = _descriptor.Descriptor(
  name='rootAddReply',
  full_name='rpc_package.rootAddReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='rpc_package.rootAddReply.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client', full_name='rpc_package.rootAddReply.client', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='rpc_package.rootAddReply.message', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trx', full_name='rpc_package.rootAddReply.trx', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ROOTADDREPLY_MESSAGEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=362,
)


_STREAMREQUEST = _descriptor.Descriptor(
  name='streamRequest',
  full_name='rpc_package.streamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client', full_name='rpc_package.streamRequest.client', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trx', full_name='rpc_package.streamRequest.trx', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='rpc_package.streamRequest.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='addNewItem', full_name='rpc_package.streamRequest.addNewItem', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=445,
)

_ROOTADDREPLY_MESSAGEENTRY.containing_type = _ROOTADDREPLY
_ROOTADDREPLY.fields_by_name['message'].message_type = _ROOTADDREPLY_MESSAGEENTRY
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['insertRequest'] = _INSERTREQUEST
DESCRIPTOR.message_types_by_name['insertReply'] = _INSERTREPLY
DESCRIPTOR.message_types_by_name['rootAddRequest'] = _ROOTADDREQUEST
DESCRIPTOR.message_types_by_name['rootAddReply'] = _ROOTADDREPLY
DESCRIPTOR.message_types_by_name['streamRequest'] = _STREAMREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'tree_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.Empty)
  })
_sym_db.RegisterMessage(Empty)

insertRequest = _reflection.GeneratedProtocolMessageType('insertRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSERTREQUEST,
  '__module__' : 'tree_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.insertRequest)
  })
_sym_db.RegisterMessage(insertRequest)

insertReply = _reflection.GeneratedProtocolMessageType('insertReply', (_message.Message,), {
  'DESCRIPTOR' : _INSERTREPLY,
  '__module__' : 'tree_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.insertReply)
  })
_sym_db.RegisterMessage(insertReply)

rootAddRequest = _reflection.GeneratedProtocolMessageType('rootAddRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROOTADDREQUEST,
  '__module__' : 'tree_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.rootAddRequest)
  })
_sym_db.RegisterMessage(rootAddRequest)

rootAddReply = _reflection.GeneratedProtocolMessageType('rootAddReply', (_message.Message,), {

  'MessageEntry' : _reflection.GeneratedProtocolMessageType('MessageEntry', (_message.Message,), {
    'DESCRIPTOR' : _ROOTADDREPLY_MESSAGEENTRY,
    '__module__' : 'tree_pb2'
    # @@protoc_insertion_point(class_scope:rpc_package.rootAddReply.MessageEntry)
    })
  ,
  'DESCRIPTOR' : _ROOTADDREPLY,
  '__module__' : 'tree_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.rootAddReply)
  })
_sym_db.RegisterMessage(rootAddReply)
_sym_db.RegisterMessage(rootAddReply.MessageEntry)

streamRequest = _reflection.GeneratedProtocolMessageType('streamRequest', (_message.Message,), {
  'DESCRIPTOR' : _STREAMREQUEST,
  '__module__' : 'tree_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.streamRequest)
  })
_sym_db.RegisterMessage(streamRequest)


_ROOTADDREPLY_MESSAGEENTRY._options = None

_TREESERVICE = _descriptor.ServiceDescriptor(
  name='TreeService',
  full_name='rpc_package.TreeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=448,
  serialized_end=598,
  methods=[
  _descriptor.MethodDescriptor(
    name='add_note_root',
    full_name='rpc_package.TreeService.add_note_root',
    index=0,
    containing_service=None,
    input_type=_ROOTADDREQUEST,
    output_type=_ROOTADDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Stream',
    full_name='rpc_package.TreeService.Stream',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_STREAMREQUEST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TREESERVICE)

DESCRIPTOR.services_by_name['TreeService'] = _TREESERVICE

# @@protoc_insertion_point(module_scope)
